### ISSUE TITLE
read_coordinates(ExodusObject) fails

### ISSUE THREAD

**Issue by thomaskroi1996** [cmhamel/Exodus.jl#28] opened 2023-06-06 10:27 UTC
Hello! 

I try to read a Exodus file with the Exodus.jl package! Installation was successful and easy, and most functions from the read me (i.e. _read_block_ids, read_blocks, read_node_set_ids, read_node_sets, read_nodal_variable_names, read_element_variable_names_) work well and without a problem!

However, when I try to read coordinates with _read_coordinates_, my terminal crashes and I am left with the following error in a VSCode pop-up: 

_The terminal process "C:\Users\Win10\AppData\Local\Programs\Julia-1.8.5\bin\julia.exe '-i', '--banner=no', '--project=c:\Users\Win10\Desktop\Arbeit\TU\work_env', 'c:\Users\Win10\.vscode\extensions\julialang.language-julia-1.47.2\scripts\terminalserver\terminalserver.jl', '\\.\pipe\vsc-jl-repl-e371abf6-13c9-4920-ac21-070935af1a66', '\\.\pipe\vsc-jl-cr-d5d8da41-2d79-4dba-aa9f-98ddec369c24', 'USE_REVISE=true', 'USE_PLOTPANE=true', 'USE_PROGRESS=true', 'ENABLE_SHELL_INTEGRATION=true', 'DEBUG_MODE=false'" terminated with exit code: 3221226356._

Sometimes there used to be a different Messge within the Terminal, when it not crashed, however I fail to reproduce that now. But for the sake of additional information, it said something with ReadOnly.... Error. And it also said that I should report the bug here!

Here is the code that reproduces the Terminal termination for me everytime.

```
exo = ExodusDatabase("read_exodus\\test.e", "r")
coords          = read_coordinates(exo)
```

I understand that the test file might be corrupt, but it is still strange behaviour since the other functions work very well, and when I use the FiniteMesh.jl package, I can easily read the coordinates!

If it is beneficial for answering the question or resolving the issues, I can ask my supervisors if I can upload the test file!

Thank you very much, I will try to help find the bug but I am happy with any help!

**Comment by cmhamel** [comment] 2023-06-06 11:21
Can you attach the exodus file in question to the issue? 

I recently removed windows testing from the CI pipeline after adding some of the quality of life tools for parallel mesh processing like decomp and epu since they are pretty flaky on Windows. It's possible there's a bug in the read_coordinates method on Windows machines at the moment.

It's interesting it's working through FiniteMesh.jl since in theory that should be calling the same (or very similar depending on version) exodusII library but through a python wrapper, at least that's my understanding of that library. So it's very possible there's a bug in the read_coordinates method on Windows but may be hard to reproduce without your exodus file.

**Comment by cmhamel** [comment] 2023-06-09 13:43
@thomaskroi1996 
I just added windows back to the CI pipeline and everything looks good there for the read_coordinates method as long as you're using Julia 1.8 or 1.9. I have not tested it beyond that. Are you running this on WSL on windows by any chance?

**Comment by thomaskroi1996** [comment] 2023-06-14 13:54
Hello! Thank you for the reply, and sorry for taking so long to get back at you!

Attached you can find the file I am trying to read!

I am using Julia 1.9, and not on WSL, just VSCode, although I do have a WSL installation with the same Julia version, perhaps there can be some conflicts? Although I tried to keep everything seperate!

Thank you!

**Comment by cmhamel** [comment] 2023-06-14 14:14
Thanks I'll take a look at this sometime next week. To eliminate any other possible conflicts can you try this in julia through something other than VSCode. E.g. the command prompt, powershell, or a julia terminal?

Just want to make sure this isn't some weird issue related to VSCode.

**Comment by cmhamel** [comment] 2023-06-14 14:46
@thomaskroi1996 

It looks like you're opening the exodus file twice with two different packages prior to closing it. This could be an issue. But I won't have a chance to confirm for a few days.

**Comment by thomaskroi1996** [comment] 2023-06-14 14:48
That is only because the read_coordinates would fail in the first place, only then did i add the FiniteMesh funtcionality. So it had the same error of my initial post, even without opening it twice! But you are right it is bad practice, and for the final result i will definitely stick with only one package, depending on which works better!

**Comment by cmhamel** [comment] 2023-06-15 08:17
@thomaskroi1996 

You likely corrupted the file then, which is quite easy to do with exodus files if not opened/closed properly. I suggest regenerating the mesh and attaching that to the issue.

**Comment by thomaskroi1996** [comment] 2023-06-15 16:05
@cmhamel 

I tried with the brand new file, unopened and directly exported from paraview, and it gives me the exact same behaviour!

**Comment by cmhamel** [comment] 2023-06-15 16:10
@thomaskroi1996 

Maybe I'm confused, but are you creating an exodus file in Paraview? I've never heard or seen this capability and if possible seems rather non-standard. Is this a file that simply has mesh node and element data or does it have output data as well?

I'm on mobile so won't have a chance to actually open the file for a few days.

**Comment by thomaskroi1996** [comment] 2023-06-15 16:20
@cmhamel 

Okay, I am not entirely sure how the file is created actually, since I am only supplied it. It is supposed to have output data as well though! I will talk more to my supervisor so i actually have more information about the file!

**Comment by thomaskroi1996** [comment] 2023-06-20 05:40
@cmhamel 

Hello again! I got more information on the file! It was created by opening opening an OpenFoam simulation in paraview, with their plugin, and then exported to an exodus file! It includes mesh as well as data!

**Comment by cmhamel** [comment] 2023-06-20 14:07
@thomaskroi1996 

I just finally got around to looking at things and something looks to be corrupted. This is the first I've encountered this error with many exodus files so this could be an artifact of the openfoam plugin perhaps. This is the error I'm receiving

[4534] signal (11.1): Segmentation fault
in expression starting at REPL[4]:1
ncx_get_float_double at /home/fractalmagic/.julia/artifacts/2d4a566ad73ee204aaae3ef08cfc954f2674e5f1/lib/libnetcdf.so (unknown line)
ncx_getn_float_double at /home/fractalmagic/.julia/artifacts/2d4a566ad73ee204aaae3ef08cfc954f2674e5f1/lib/libnetcdf.so (unknown line)
getNCvx_float_double at /home/fractalmagic/.julia/artifacts/2d4a566ad73ee204aaae3ef08cfc954f2674e5f1/lib/libnetcdf.so (unknown line)
readNCv at /home/fractalmagic/.julia/artifacts/2d4a566ad73ee204aaae3ef08cfc954f2674e5f1/lib/libnetcdf.so (unknown line)
NC3_get_vara at /home/fractalmagic/.julia/artifacts/2d4a566ad73ee204aaae3ef08cfc954f2674e5f1/lib/libnetcdf.so (unknown line)
NC_get_vara at /home/fractalmagic/.julia/artifacts/2d4a566ad73ee204aaae3ef08cfc954f2674e5f1/lib/libnetcdf.so (unknown line)
NC_get_var at /home/fractalmagic/.julia/artifacts/2d4a566ad73ee204aaae3ef08cfc954f2674e5f1/lib/libnetcdf.so (unknown line)
nc_get_var_double at /home/fractalmagic/.julia/artifacts/2d4a566ad73ee204aaae3ef08cfc954f2674e5f1/lib/libnetcdf.so (unknown line)
ex_get_coord at /home/fractalmagic/.julia/artifacts/bc5df6750d5ee879a8e8c27d2f5de9a134d282bb/lib/libexodus.so (unknown line)
ex_get_coord! at /home/fractalmagic/Exodus.jl/src/Coordinates.jl:7
unknown function (ip: 0x7fa3a69030a4)
read_coordinates at /home/fractalmagic/Exodus.jl/src/Coordinates.jl:40
unknown function (ip: 0x7fa3a6902ef2)
corrupted size vs. prev_size

[4534] signal (6.-6): Aborted
in expression starting at REPL[4]:1

This could take a great deal of effort to debug unfortunately. If you want example files, you can pull the repo and take a look in the test folder. There are several simple example meshes.

It's interesting though I'm able to open things in paraview just fine and I can ncdump the data to see the file in fact has data in it.

I'll try to poke at this a little bit more over the next few days.

**Comment by cmhamel** [comment] 2023-06-22 10:28
@thomaskroi1996 

Here is a work around for you. This issue is likely in the converter you're using or how you're calling the converter. The exodusII library thinks your file should be in single precision floating point numbers yet your coordinates and output fields are in double precision floating point numbers thus causing a memory allocation error.

`using Exodus
exo = ExodusDatabase("test.e", "r")
exo = ExodusDatabase(exo.exo, exo.mode, exo.M, exo.I, exo.B, Float64, exo.init)
coords = read_coordinates(exo)
display(coords)
close(exo)`

where `test.e` is your exodus file. You may need to change that path. Basically what this is doing is hardcoding the ExodusDatabase to Float64 rather than reading it as Float32 incorrectly.

Hope this helps!

**Comment by thomaskroi1996** [comment] 2023-06-25 15:58
Hello! Thank you so much, that helped a lot! I will talk to my supervisor about this issue and see what we do next then! For now, this works wonderfully, thank you!

**Closed** 2023-06-29 22:30 UTC
